#server:
#  port: 9000
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true
#
#  datasource:
#    url: jdbc:mysql://ssgnew.cunojsn8ha3m.ap-northeast-2.rds.amazonaws.com:3306/ssgnew?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
#    username: ssgnew
#    password: ssgnewnew
#    driver-class-name: com.mysql.cj.jdbc.Driver


