server:
  port: 8080
#spring:
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 500MB
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        format_sql: true
#
#  datasource:
#    url: jdbc:mysql://ssgnew.cunojsn8ha3m.ap-northeast-2.rds.amazonaws.com/ssgnew?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
#    username: ssgnew
#    password: ssgnewnew
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    url: jdbc:mysql://localhost:3308/MyssgDB
#    password: '1234'
    url: jdbc:mysql://localhost:3306/ssgnew
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  profiles:
    include: oauth

api:
  naver:
    client_id: yMLNmzMmwJfV81HW82NF
    client_secret: HDdhF9HBBG

  kakao:
    client_id: 389b73fe882b1f88e4efd7b0372ac800

cloud:
  aws:
    credentials:
      accessKey: AKIA4CDIXXFFKCY4FC7K
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

sms:
  senderPhone: 01036699883
  serviceId: ncp:sms:kr:291731081252:ssg
  accessKey: crj2Y2dosCMKfs7kNIMC
  secretKey: 5AjZPRf8vjalFhoDFieM6HZctTC7tAIqp3mfMkc6







